#pragma once

#define ENABLE_COLLISION_BOXES
//#define ENABLE_AXIS_FOR_COLLISION_BOXES

#if defined(ENABLE_COLLISION_BOXES) || defined(ENABLE_AXIS_FOR_COLLISION_BOXES)
	#define ENABLE_COLLISION_DEBUG_DRAW 
#endif